import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'English': 'English',
          'Urdu': 'Urdu',
          'Select your preferred language': 'Select your preferred language',
          'Hi, Welcome Back! 👋': 'Hi, Welcome Back! 👋',
          'Hello again, you’ve been missed!':
              'Hello again, you’ve been missed!',
          'Email': 'Email',
          'Enter Your Email': 'Enter Your Email',
          'Please enter a valid email': 'Please enter a valid email',
          'Password': 'Password',
          'Enter Your Password': 'Enter Your Password',
          'Password not be empty!': 'Password not be empty!',
          'Password must be greater than 5 character!':
              'Password must be greater than 5 character!',
          'Remember Me': 'Remember Me',
          'Forgot Password': 'Forgot Password',
          'Login': 'Login',
          'Or With': 'Or With',
          'Don’t have an account ?   ': 'Don’t have an account ?   ',
          'Sign Up': 'Sign Up',
          'Don’t worry! It happens. Please enter the\nemail address associated with your account.':
              'Don’t worry! It happens. Please enter the\nemail address associated with your account.',
          'Submit': 'Submit',
          'Forgot Password?': 'Forgot Password?',
          'Reset Password': 'Reset Password',
          'Confirm Password': 'Confirm Password',
          'Already have an account ?   ': 'Already have an account ?   ',
          'Create an account': 'Create an account',
          'Connect with your friends today!':
              'Connect with your friends today!',
          'Full Name': 'Full Name',
          'Enter Your Name': 'Enter Your Name',
          'Name not be empty!': 'Name not be empty!',
          'Phone Number': 'Phone Number',
          'Enter Your Phone Number': 'Enter Your Phone Number',
          'Please enter a valid phone number':
              'Please enter a valid phone number',
          'Enter Verification Code': 'Enter Verification Code',
          'Please enter the otp code\n we sent you on the registered\n phone number with student':
              'Please enter the otp code\n we sent you on the registered\n phone number with student',
          'I did not receive the OTP': 'I did not receive the OTP',
          'Resend Code': 'Resend Code',
          'Searching Students by given\n phone numbers':
              'Searching Students by given\n phone numbers',
          'Skip': 'Skip',
          'Home': 'Home',
          'Dashboard': 'Dashboard',
          'Pay Fee': 'Pay Fee',
          'Setting': 'Setting',
          'Select Language': 'Select Language',
          'Language': 'Language',
          'Your Account': 'Your Account',
          'Personal Information': 'Personal Information',
          'Abdul Waheed': 'Abdul Waheed',
          'Card and Account': 'Card and Account',
          'Places and Addresses': 'Places and Addresses',
          'Notifications': 'Notifications',
          'Benefits': 'Benefits',
          'Rewards': 'Rewards',
          'You have 560 points': 'You have 560 points',
          'Support': 'Support',
          'Help': 'Help',
          'Rate the app': 'Rate the app',
          'Preferences': 'Preferences',
          'Sign Out': 'Sign Out',
          'Add': 'Add',
          'Profile': 'Profile',
          'Saved Payment Methods': 'Saved Payment Methods',
          'Primary': 'Primary',
          'Add New': 'Add New',
          'Add Payment Method': 'Add Payment Method',
          'What\'s Your Email?': 'What\'s Your Email?',
          'Change Password': 'Change Password',
          'Gender': 'Gender',
          'Not added': 'Not added',
          'Date of Birth': 'Date of Birth',
          'Card/Account Details': 'Card/Account Details',
          'Select a new primary payment method':
              'Select a new primary payment method',
          'We will use this payment method for all your\norders':
              'We will use this payment method for all your\norders',
          'Remove card/account': 'Remove card/account',
          'We will use this payment method out from the list':
              'We will use this payment method out from the list',
          'Remove This Payment Method': 'Remove This Payment Method',
          'We will remove it from your list of\npayment method saved.':
              'We will remove it from your list of\npayment method saved.',
          'Remove Payment Method': 'Remove Payment Method',
          'Keep Payment Method': 'Keep Payment Method',
          'Welcome Abdul,': 'Welcome Abdul,',
          'FeePay Mart': 'FeePay Mart',
          'Add Student': 'Add Student',
          'Students': 'Students',
          'Select your language': 'Select your language',
          'Student Dashboard': 'Student Dashboard',
          'Select Other Student': 'Select Other Student',
          'Credit/Debit Card': 'Credit/Debit Card',
          'Bank Account': 'Bank Account',
          'E-Wallet': 'E-Wallet',
          'Mastercard': 'Mastercard',
          'Visa': 'Visa',
          'Muhammad Ali Nawaz': 'Muhammad Ali Nawaz',
          'Adbul Waheed': 'Adbul Waheed',
          'Horizon Public School': 'Horizon Public School',
          'Kips School': 'Kips School',
          'Class': 'Class',
          'Institute': 'Institute',
          'Today\'s': 'Today\'s',
          'This Week': 'This Week',
          'Fee Due': 'Fee Due',
          'PTM': 'PTM',
          'Confirm': 'Confirm',
          'M.Asad fee is due on 10/01/23.': 'M.Asad fee is due on 10/01/23.',
          'Parent teacher meeting has been scheduled for next Saturday.':
              'Parent teacher meeting has been scheduled for next Saturday.',
          'Pay Now!': 'Pay Now!',
          'Add to Calendar': 'Add to Calendar',
          'Student': 'Student',
          'Fees': 'Fees',
          'Facility': 'Facility',
          'Classes': 'Classes',
          'Library': 'Library',
          'Calender': 'Calender',
          'Report': 'Report',
          'Chat': 'Chat',
          'Feedback': 'Feedback',
          'Setup': 'Setup',
          'Blog': 'Blog',
          'More+': 'More+',
          'Fee Pay': 'Fee Pay',
          '+ Add new Payment method': '+ Add new Payment method',
          'You won’t be charged until you review the\nnext page':
              'You won’t be charged until you review the\nnext page',
          'Choose a payment method': 'Choose a payment method',
          'Due Date': 'Due Date',
          'Fee Payable for the month of\n December 2022':
              'Fee Payable for the month of\n December 2022',
          'PKR 7,000': 'PKR 7,000',
          'Client': 'Client',
          'Cancel': 'Cancel',
          'Expiry Date': 'Expiry Date',
          'CCV': 'CCV',
          'Enter 16 digit card no': 'Enter 16 digit card no',
          'Card Number': 'Card Number',
          'Meezan Bank': 'Meezan Bank',
          'EasyPaisa': 'EasyPaisa',
          'JazzCash': 'JazzCash',
          'Allied Bank': 'Allied Bank ',
          'Account Number': 'Account Number',
          'Account Number/IBAN': 'Account Number/IBAN',
          'Search (e.g. bank name)...': 'Search (e.g. bank name)...',
          'Please enter': 'Please enter',
          '11 digit account number': '11 digit account number',
          'Congratulations': 'Congratulations',
          'Transaction has been completed\n Successfully':
              'Transaction has been completed\n Successfully',
          'Next Monthly fee due on\n 10 Jan,2023':
              'Next Monthly fee due on\n 10 Jan,2023',
          '3 Points Earn': '3 Points Earn',
          'Total Points 255': 'Total Points 255',
          'Go to Wallet': 'Go to Wallet',
          'Student has been added\n Successfully':
              'Student has been added\n Successfully',
          'You have successfully added\n your':
              'You have successfully added\n your',
          'Wallet': 'Wallet',
          'Coins': 'Coins',
          'Cash': 'Cash',
          '100 Coins': '100 Coins',
          'Link Account': 'Link Account',
          '= PKR 1,000': '= PKR 1,000',
          'You currently have': 'You currently have',
          'Withdrawal Money': 'Withdrawal Money',
          'Transfer': 'Transfer',
          'Transfer to Bank/E-Wallet': 'Transfer to Bank/E-Wallet',
          'Withdraw': 'Withdraw',
          'Recipient must be a PayFee user': 'Recipient must be a PayFee user',
          'send to a known crypto address via\ncrypto network':
              'send to a known crypto address via\ncrypto network',
          'Send via email/ Phone/ Pay ID': 'Send via email/ Phone/ Pay ID',
          'Send via crypto network': 'Send via crypto network',
          'Go to Home': 'Go to Home',
          'has been successfully transferred to your':
              'has been successfully transferred to your',
          'Download Receipt': 'Download Receipt',
          'Remaining Balance': 'Remaining Balance',
          'Withdraw Crypto': 'Withdraw Crypto',
          'Select Coin': 'Select Coin',
          'Select Bank': 'Select Bank',
          'Withdraw to': 'Withdraw to',
          'Address': 'Address',
          'Network': 'Network',
          'Wallet address automatically matched to\ncorresponding network':
              'Wallet address automatically matched to\ncorresponding network',
          'BTC Bitcoin (BTC)': 'BTC Bitcoin (BTC)',
          'BTC available': 'BTC available',
          'MAX   BTC': 'MAX   BTC',
          '100 BTC /100 BTC  ': '100 BTC /100 BTC  ',
          '24h remaining limit': '24h remaining limit',
          'Receive amount': 'Receive amount',
          '0.995000 BTC': '0.995000 BTC',
          'Search School': 'Search School',
          'Next': 'Next',
          "Wapda Town, Lahore": "Wapda Town, Lahore",
          "Johar Town, Lahore": "Johar Town, Lahore",
          'Search schools name...': 'Search schools name...',
          'School name dos\'t match': 'School name dos\'t match',
          'To add student, please search using\n school name.':
              'To add student, please search using\n school name.',
          'Search Student': 'Search Student',
          'Search Student ID, Name...': 'Search Student ID, Name...',
          'Student ID': 'Student ID',
          'Grade': 'Grade',
          'Student Id or Name dos\'t match': 'Student Id or Name dos\'t match',
          'You can search student by\n Student ID and Name.':
              'You can search student by\n Student ID and Name.',
          'Confirm Student': 'Confirm Student',
          '1 Aug, 2004': '1 Aug, 2004',
          '2 June, 2000': '2 June, 2000',
          'Back': 'Back',
          'Institute Name': 'Institute Name',
          'Student Name': 'Student Name',
          'Search': 'Search',
          'Featured Categories': 'Featured Categories',
          'Uniforms': 'Uniforms',
          'Craft Supplies': 'Craft Supplies',
          'Paint Brushes': 'Paint Brushes',
          'Painting Canvases': 'Painting Canvases',
          'Sketchbooks': 'Sketchbooks',
          'Acrylic Paints': 'Acrylic Paints',
          'Brush Pen': 'Brush Pen',
          'Featured Products': 'Featured Products',
          'View All': 'View All',
          'Clip Pack': 'Clip Pack',
          'Rs 500': 'Rs 500',
          'Rs 2,000': 'Rs 2,000',
          'Multi color sticky notes very good quality':
              'Multi color sticky notes very good quality',
          'All Products': 'All Products',
          'Product Detail': 'Product Detail',
          'Added To Cart': 'Added To Cart',
          'SHOW CART': 'SHOW CART',
          'Add to Cart': 'Add to Cart',
          'Buy Now': 'Buy Now',
          'Price:': 'Price:',
          'Rs': 'Rs',
          'Total Price:': 'Total Price:',
          'Quantity:': 'Quantity:',
          'available': 'available',
          'Brand:': 'Brand:',
          'Mont Marte': 'Mont Marte',
          'Description:': 'Description:',
          'Describe something or someone. [count] Reporters called the scene “a disaster area,” and I think that was an accurate description. I applied for the position after reading the job description.':
              'Describe something or someone. [count] Reporters called the scene “a disaster area,” and I think that was an accurate description. I applied for the position after reading the job description.',
          'Seller policy': 'Seller policy',
          'Return policy': 'Return policy',
          'Support policy': 'Support policy',
          'Product you may also like': 'Product you may also like',
          'Shopping Cart': 'Shopping Cart',
          'Read Less': 'Read Less',
          'Read More': 'Read More',
          'PROCEED TO SHIPPING': 'PROCEED TO SHIPPING',
          'There is no Item in Cart': 'There is no Item in Cart',
          'Stationery Shop': 'Stationery Shop',
          'PROCEED TO CHECKOUT': 'PROCEED TO CHECKOUT',
          'Attendance': 'Attendance',
          'Attendance percentage division:': 'Attendance percentage division:',
          'Well Done': 'Well Done',
          'I\'m Concerned': 'I\'m Concerned',
          'Seriously Worried': 'Seriously Worried',
          'Jan': 'Jan',
          'Feb': 'Feb',
          'Mar': 'Mar',
          'Apr': 'Apr',
          'May': 'May',
          'Jun': 'Jun',
          'July': 'July',
          'Aug': 'Aug',
          'Sep': 'Sep',
          'Oct': 'Oct',
          'Nov': 'Nov',
          'Dec': 'Dec',
          'from': 'from',
          'Time Table of Classes:': 'Time Table of Classes:',
          'Monday': 'Monday',
          'Maths': 'Maths',
          'Ms.Daina': 'Ms.Daina',
          'Ms.Sadia': 'Ms.Sadia',
          'Computer': 'Computer',
          'Friday': 'Friday',
          'Thursday': 'Thursday',
          'Wednesday': 'Wednesday',
          'Tuesday': 'Tuesday',
          'Paid': 'Paid',
          'Monthly Dues': 'Monthly Dues',
          'Monthly Fee': 'Monthly Fee',
          'Payment History': 'Payment History',
          'Dues': 'Dues'
        },
        'ur_PK': {
          'Dues': 'واجبات',
          'Payment History': 'ادائیگی کی سرگزشت',
          'Monthly Fee': 'ماہانہ فیس',
          'Monthly Dues': 'ماہانہ واجبات',
          'Paid': 'ادا کیا',
          'Tuesday': 'منگل',
          'Wednesday': 'بدھ',
          'Thursday': 'جمعرات',
          'Friday': 'جمعہ',
          'Computer': 'کمپیوٹر',
          'Ms.Sadia': 'مس سعدیہ',
          'Ms.Daina': 'مس ڈائنا',
          'Maths': 'ریاضی',
          'Monday': 'پیر',
          'Time Table of Classes:': 'کلاسز کا ٹائم ٹیبل:',
          'from': 'سے',
          'Jan': 'جنوری',
          'Feb': 'فروری',
          'Mar': 'مارچ',
          'Apr': 'اپریل',
          'May': 'مئی',
          'Jun': 'جون',
          'July': 'جولائی',
          'Aug': 'اگست',
          'Sep': 'ستمبر',
          'Oct': 'اکتوبر',
          'Nov': 'نومبر',
          'Dec': 'دسمبر',
          'Seriously Worried': 'سنجیدگی سے پریشان',
          'I\'m Concerned': 'میں فکر مند ہوں',
          'Well Done': 'بہت اچھے',
          'Attendance percentage division:': 'حاضری فیصد تقسیم:',
          'Attendance': 'حاضری',
          'PROCEED TO CHECKOUT': 'چیک آؤٹ کے لیے آگے بڑھیں',
          'Stationery Shop': 'سٹیشنری کی دکان',
          'There is no Item in Cart': 'کارٹ میں کوئی چیز نہیں ہے',
          'PROCEED TO SHIPPING': 'شیپنگ کے لیے آگے بڑھیں',
          'Read More': 'مزید پڑھ',
          'Read Less': 'کم پڑھیں',
          'Shopping Cart': 'خریداری کارٹ',
          'Product you may also like': 'پروڈکٹ آپ کو بھی پسند آ سکتی ہے',
          'Support policy': 'سپورٹ پالیسی',
          'Return policy': 'واپسی کی پالیسی',
          'Seller policy': 'بیچنے والے کی پالیسی',
          'Describe something or someone. [count] Reporters called the scene “a disaster area,” and I think that was an accurate description. I applied for the position after reading the job description.':
              'کچھ یا کسی کی وضاحت کریں۔ رپورٹرز نے اس منظر کو "ایک آفت زدہ علاقہ" کہا اور میرے خیال میں یہ ایک درست تفصیل تھی۔ میں نے نوکری کی تفصیل پڑھنے کے بعد اس عہدے کے لیے درخواست دی۔',
          'Description:': 'تفصیل:',
          'Mont Marte': 'مونٹ مارٹ',
          'Brand:': 'برانڈ:',
          'available': 'دستیاب',
          'Quantity:': 'مقدار:',
          'Total Price:': 'کل قیمت:',
          'Rs': 'روپے',
          'Price:': 'قیمت:',
          'Buy Now': 'ابھی خریدئے',
          'Add to Cart': 'کارٹ میں شامل',
          'SHOW CART': 'کارٹ دکھائیں',
          'Added To Cart': 'کارٹ میں شامل کیا گیا',
          'Product Detail': 'مصنوعات کی تفصیلات',
          'All Products': 'تمام مصنوعات',
          'Multi color sticky notes very good quality':
              'ملٹی کلر چسپاں نوٹ بہت اچھے معیار کے ہیں۔',
          'Rs 500': '500 روپے',
          'Rs 2,000': '2,000 روپے',
          'Clip Pack': 'کلپ پیک',
          'View All': 'سب دیکھیں',
          'Featured Products': 'نمایاں مصنوعات',
          'Uniforms': 'یونیفارم',
          'Craft Supplies': 'دستکاری کی فراہمی',
          'Paint Brushes': 'پینٹ برش',
          'Painting Canvases': 'پینٹنگ کینوس',
          'Sketchbooks': 'خاکے کی کتابیں',
          'Acrylic Paints': 'ایکریلک پینٹس',
          'Brush Pen': 'برش قلم',
          'Featured Categories': 'نمایاں زمرہ جات',
          'Search': 'تلاش',
          'Student Name': 'طالب علم کا نام',
          'Institute Name': 'انسٹی ٹیوٹ کا نام',
          'Back': 'پیچھے',
          '1 Aug, 2004': '1 اگست، 2004',
          '2 June, 2000': '2 جون 2000',
          'Confirm Student': 'طالب علم کی تصدیق کریں',
          'You can search student by\n Student ID and Name.':
              'آپ طالب علم کو طالب علم کی شناخت اور\n نام سے تلاش کر سکتے ہیں۔',
          'Student Id or Name dos\'t match':
              'طالب علم کی شناخت یا نام مماثل نہیں ہے',
          'Grade': 'گریڈ',
          'Student ID': 'طالب علم کی شناخت',
          'Search Student ID, Name...': 'طالب علم کی شناخت، نام تلاش کریں...',
          'Search Student': 'طلبہ تلاش کریں',
          "Wapda Town, Lahore": "واپڈا ٹاؤن، لاہور",
          "Johar Town, Lahore": "جوہر ٹاؤن، لاہور",
          'To add student, please search using\n school name.':
              'طالب علم کو شامل کرنے کے لیے، برائے مہربانی اسکول کا نام\n استعمال کرکے تلاش کریں۔',
          'School name dos\'t match': 'اسکول کا نام مماثل نہیں ہے',
          'Search schools name...': 'سکولوں کا نام تلاش کریں...',
          'Next': 'اگلے',
          'Search School': 'سکول تلاش کریں',
          '0.995000 BTC': '0.995000 بی ٹی سی',
          'Receive amount': 'رقم وصول کریں',
          '24h remaining limit': '24 گھنٹے باقی کی حد',
          '100 BTC /100 BTC  ': '100 بی ٹی سی / 100 بی ٹی سی',
          'MAX   BTC': 'زیادہ سے زیادہ بی ٹی سی',
          'BTC available': 'بی ٹی سی دستیاب ہے',
          'BTC Bitcoin (BTC)': '(بی ٹی سی)  بٹ کوائن  بی ٹی سی',
          'Network': 'نیٹ ورک',
          'Address': 'پتہ',
          'Wallet address automatically matched to\ncorresponding network':
              'پرس کا پتہ خود بخود مماثل نیٹ ورک سے\nمماثل ہے',
          'Withdraw to': 'واپس لیں',
          'Select Bank': 'بینک کو منتخب کریں',
          'Select Coin': 'سکے کو منتخب کریں',
          'Withdraw Crypto': 'کرپٹو واپس لیں',
          'Download Receipt': 'رسید ڈاؤن لوڈ کریں',
          'Go to Home': 'گھر جاو',
          'Withdraw': 'بقیہ رقم',
          'has been successfully transferred to your':
              'آپ کو کامیابی سے منتقل کر دیا گیا ہے',
          'Remaining Balance': 'واپس لینا',
          'Recipient must be a PayFee user':
              'وصول کنندہ ایک PayFee صارف ہونا چاہیے۔',
          'send to a known crypto address via\ncrypto network':
              'کرپٹو نیٹ ورک کے ذریعے معروف کرپٹو \nایڈریس پر بھیجیں۔',
          'Send via email/ Phone/ Pay ID':
              'ای میل/ فون/ پے آئی ڈی کے ذریعے بھیجیں۔',
          'Send via crypto network': 'کرپٹو نیٹ ورک کے ذریعے بھیجیں۔',
          'Transfer to Bank/E-Wallet': 'بینک/ای والیٹ میں منتقلی',
          'Transfer': 'منتقلی',
          'Withdrawal Money': 'اکاؤنٹ لنک کریں',
          'You currently have': 'فی الحال آپ کے پاس ہے',
          'Cash': 'نقد',
          'Link Account': 'اکاؤنٹ لنک کریں',
          '100 Coins': '100 سکے',
          '= PKR 1,000': '= روپے 1,000',
          'Coins': 'سکے',
          'Wallet': 'پرس',
          'You have successfully added\n your':
              'آپ نے کامیابی کے ساتھ اپنا شامل کر لیا ہے',
          'Student has been added\n Successfully':
              'طالب علم کو کامیابی کے ساتھ\n شامل کر دیا گیا ہے۔',
          'Go to Wallet': 'پرس پر جائیں',
          'Total Points 255': 'کل پوائنٹس 255',
          '3 Points Earn': '3 پوائنٹس کمائیں',
          'Next Monthly fee due on\n 10 Jan,2023':
              'اگلی ماہانہ فیس\n 10 جنوری، 2023 کو واجب الادا ہے۔',
          'Transaction has been completed\n Successfully':
              'ٹرانزیکشن مکمل ہو گیا ہے\n کامیابی کے ساتھ',
          'Congratulations': 'مبارک ہو',
          '11 digit account number': '11 ہندسوں کا اکاؤنٹ نمبر',
          'Please enter': 'درج کریں',
          'Account Number/IBAN': 'اکاؤنٹ نمبر/IBAN',
          'Search (e.g. bank name)...': 'تلاش کریں (جیسے بینک کا نام)...',
          'Card Number': 'کارڈ نمبر',
          'Account Number': 'اکاؤنٹ نمبر',
          'Allied Bank': 'الائیڈ بینک',
          'Meezan Bank': 'میزان بینک',
          'Enter 16 digit card no': '16 ہندسوں کا کارڈ نمبر درج کریں',
          'CCV': 'سی سی وی',
          'JazzCash': 'جاز کیش',
          'EasyPaisa': 'ایزی پیسہ',
          'Expiry Date': 'خاتمے کی تاریخ',
          'Cancel': 'منسوخ کریں',
          'Client': 'کلائنٹ',
          'PKR 7,000': '7,000 روپے',
          'Fee Payable for the month of\n December 2022':
              'دسمبر 2022 کے مہینے کے لیے \nقابل ادائیگی فیس',
          'Due Date': 'اخری تاریخ',
          'Choose a payment method': 'ادائیگی کا طریقہ منتخب کریں',
          '+ Add new Payment method': '+ ادائیگی کا نیا طریقہ شامل کریں۔',
          'You won’t be charged until you review the\nnext page':
              'آپ سے اس وقت تک چارج نہیں لیا جائے گا جب تک کہ آپ \nاگلے صفحہ کا جائزہ نہیں لیتے',
          'Student': 'طالب علم',
          'Fees': 'فیس',
          'Facility': 'سہولت',
          'Classes': 'کلاسز',
          'Library': 'کتب خانہ',
          'Calender': 'کیلنڈر',
          'Report': 'رپورٹ',
          'Chat': 'چیٹ',
          'Feedback': 'رائے',
          'Setup': 'سیٹ اپ',
          'Blog': 'بلاگ',
          'More+': 'مزید+',
          'Add to Calendar': 'کیلنڈر میں شامل کریں',
          'Pay Now!': 'اب ادا!',
          'Confirm': 'تصدیق کریں',
          'Parent teacher meeting has been scheduled for next Saturday.':
              'والدین اساتذہ کی میٹنگ اگلے ہفتہ کو مقرر کی گئی ہے۔',
          'M.Asad fee is due on 10/01/23.':
              'ایم اسد کی فیس 10/01/23 کو واجب الادا ہے۔',
          'PTM': 'پی ٹی ایم',
          'Fee Due': 'فیس واجب الادا',
          'This Week': 'اس ہفتے',
          'Today\'s': 'آج کا',
          'Institute': 'انسٹی ٹیوٹ',
          'Class': 'کلاس',
          'Kips School': 'کِپس سکول',
          'Horizon Public School': 'ہورائزن پبلک سکول',
          'Adbul Waheed': 'عبدالوحید',
          'Muhammad Ali Nawaz': 'محمد علی نواز',
          'Visa': 'ویزا',
          'Mastercard': 'ماسٹر کارڈ',
          'E-Wallet': 'ای-والیٹ',
          'Bank Account': 'بینک اکاؤنٹ',
          'Credit/Debit Card': 'کریڈٹ/ڈیبٹ کارڈ',
          'Select Other Student': 'دوسرے طالب علم کو منتخب کریں',
          'Student Dashboard': 'طالب علم ڈیش بورڈ',
          'Select your language': 'اپنی زبان منتخب کریں',
          'Students': 'طلبہ',
          'Add Student': 'طالب علم شامل کریں',
          'FeePay Mart': 'فی پے مارٹ',
          'Fee Pay': 'فی پے',
          'Welcome Abdul,': 'خوش آمدید عبدل،',
          'Keep Payment Method': 'ادائیگی کا طریقہ رکھیں',
          'Remove Payment Method': 'ادائیگی کا طریقہ ہٹائیں',
          'We will remove it from your list of\npayment method saved.':
              'ہم اسے آپ کے محفوظ کردہ ادائیگی کے طریقوں کی فہرست سے ہٹا دیں گے۔',
          'Remove This Payment Method': 'یہ ادائیگی کا طریقہ ہٹا دیں',
          'We will use this payment method out from the list':
              'ہم اس ادائیگی کا طریقہ استعمال کریں گے فہرست سے باہر',
          'Remove card/account': 'کارڈ/اکاؤنٹ ہٹائیں',
          'We will use this payment method for all your\norders':
              'ہم آپ کے تمام آرڈرز کے لیے ادائیگی کا یہ طریقہ \nاستعمال کریں گے',
          'Select a new primary payment method':
              'ایک نیا بنیادی ادائیگی کا طریقہ منتخب کریں',
          'Card/Account Details': 'کارڈ/اکاؤنٹ کی تفصیلات',
          'Date of Birth': 'پیدائش کی تاریخ',
          'Not added': 'شامل نہیں کیا گیا',
          'Gender': 'صنف',
          'Change Password': 'پاس ورڈ تبدیل کریں',
          'What\'s Your Email?': 'آپ کا ای میل کیا ہے؟',
          'Profile': 'پروفائل',
          'Add': 'شامل کریں',
          'Add Payment Method': 'ادائیگی کا طریقہ شامل کریں',
          'Add New': 'نیا شامل کریں',
          'Primary': 'پرائمری',
          'Saved Payment Methods': 'محفوظ ادائیگی کے طریقے',
          'Sign Out': 'باہر جائیں',
          'Preferences': 'ترجیحات',
          'Rate the app': 'ایپ کی درجہ بندی کریں',
          'Support': 'سپورٹ',
          'Help': 'مدد',
          'You have 560 points': 'آپ کے پاس 560 پوائنٹس ہیں',
          'Rewards': 'انعامات',
          'Benefits': 'فوائد',
          'Notifications': 'اطلاعات',
          'Places and Addresses': 'مقامات اور پتے',
          'Card and Account': 'کارڈ اور اکاؤنٹ',
          'Abdul Waheed': 'عبدالوحید',
          'Personal Information': 'ذاتی معلومات',
          'Your Account': 'آپ کا کھاتہ',
          'English': 'انگریزی',
          'Urdu': 'اردو',
          'Select your preferred language': 'اپنی پسند کی زبان منتخب کریں۔',
          'Hi, Welcome Back! 👋': 'ہیلو، واپس خوش آمدید! 👋',
          'Hello again, you’ve been missed!':
              'ایک بار پھر ہیلو، آپ کو یاد کیا گیا ہے!',
          'Email': 'ای میل',
          'Enter Your Email': 'اپنا ای میل درج کریں',
          'Please enter a valid email': 'ایک درست ای میل درج کریں',
          'Password': 'پاس ورڈ',
          'Enter Your Password': 'اپنا پاس ورڈ درج کریں',
          'Password not be empty!': 'پاس ورڈ خالی نہ ہو!',
          'Password must be greater than 5 character!':
              'پاس ورڈ 5 حروف سے بڑا ہونا چاہیے!',
          'Remember Me': 'مجھے پہچانتے ہو',
          'Forgot Password': 'پاسورڈ بھول گے',
          'Forgot Password?': 'پاسورڈ بھول گے؟',
          'Login': 'لاگ ان کریں',
          'Or With': 'یا ساتھ',
          'Don’t have an account ?   ': 'کیا آپ کا اکاؤنٹ نہیں ہے؟   ',
          'Sign Up': 'سائن اپ',
          'Don’t worry! It happens. Please enter the\nemail address associated with your account.':
              'فکر مت کرو! یہ ہوتا ہے. براہ کرم اپنے اکاؤنٹ سے وابستہ\n ای میل ایڈریس درج کریں۔',
          'Submit': 'جمع کرائیں',
          'Reset Password': 'پاس ورڈ ری سیٹ',
          'Confirm Password': 'پاس ورڈ کی تصدیق کریں',
          'Already have an account ?   ': 'پہلے سے ہی ایک اکاؤنٹ ہے؟    ',
          'Create an account': 'کھاتا کھولیں',
          'Connect with your friends today!': 'آج ہی اپنے دوستوں سے جڑیں!',
          'Full Name': 'پورا نام',
          'Enter Your Name': 'اپنا نام درج کریں',
          'Name not be empty!': 'نام خالی نہ ہو!',
          'Phone Number': 'فون نمبر',
          'Enter Your Phone Number': 'اپنا فون نمبر درج کریں',
          'Please enter a valid phone number': 'ایک درست فون نمبر درج کریں',
          'Enter Verification Code': 'تصدیقی کوڈ درج کریں',
          'Please enter the OTP code\n we sent you on the registered\n phone number with student':
              'براہ کرم OTP کوڈ درج کریں\n ہم نے آپ کو رجسٹرڈ \nفون نمبر پر طالب علم کے ساتھ بھیجا ہے۔',
          'I did not receive the OTP': 'مجھے OTP موصول نہیں ہوا۔',
          'Resend Code': 'کوڈ دوبارہ بھیجیں۔',
          'Searching Students by given\n phone numbers':
              'دیے گئے فون نمبرز کے ذریعے \nطلباء کو تلاش کرنا',
          'Skip': 'چھوڑ دو',
          'Home': 'گھر',
          'Dashboard': 'ڈیش بورڈ',
          'Pay Fee': 'فی پے',
          'Setting': 'ترتیب',
          'Select Language': 'زبان منتخب کریں',
          'Language': 'زبان'
        },
      };
}
